version: '3.4'

services:
  webapi:
    container_name: webapi
    image: god0nlyknows/tbk622webapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:9000
    ports:
    - "9000:9000"

    networks:
          vpcbr:
            ipv4_address: 10.5.0.5

  reactclient:
        container_name: reactclient
        image: god0nlyknows/tbk622react
        restart: always
        environment:
          - WEB_API_BASE_URL=http://10.5.0.5:9000
        ports:
          - "3000:3000"
        depends_on:
          - "webapi"
        networks:
          vpcbr:
            ipv4_address: 10.5.0.6
        

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1